### PR TITLE
fix

### PR DESCRIPTION
**Pull request by thorewi**

### CODE REVIEW

**Comment by martenb** [comment]
AFAIK fixes https://github.com/Kdyby/Translation/issues/178

**Comment by jkavalik** [comment]
Maybe this could add a conflict clause to composer.json for older latte?

**Comment by lulco** [comment]
@enumag can you check this PR?

**Review by enumag — APPROVED** [review]

**Review by enumag — APPROVED** [review]

**Comment by enumag** [comment]
Please send a PR with adding PHP 7.3 and 7.4 to travis. #10 did it for master but we need it for 2.0 branch as well in order to release 2.0.1. Thanks.

**Comment by jkavalik** [comment]
so after this fix I am now getting
`Declaration of Kdyby\StrictObjects\Scream::__get(string $name) should be compatible with & Latte\Macros\MacroSet::__get(string $name)`
and I am not sure if that can be fixed simply by adding & or if it means problems.

-- EDIT --
Solved by correcting the tag

**Pull request merged**
