### PR TITLE
Split Scream trait into smaller units, use PHPUnit, refactoring

### PR DESCRIPTION
**Pull request by Majkl578**
Compose Scream from smaller traits, some refactoring here and there around Suggester and exceptions.

_To be retargeted to master after #5 is merged._

### CODE REVIEW

**Review by ping-localhost — APPROVED** [review]

**Comment by ping-localhost** [comment]
@Majkl578 The only thing that I'm, personally, missing is `@covers` inside the unit tests, but I'm not sure why you didn't add them. If you are planning on adding them, it might be useful to set `forceCoversAnnotation` to `true` in the PHPUnit configuration file.

**Review by enumag — APPROVED** [review]
I don't really see a point in having all the separate traits but if you prefer it that way...

**Comment by Majkl578** [comment]
@enumag One colleague had recently an issue with `__isset()` (only) throwing. Another possible use case is using Scream with Doctrine repositories while keeping magic findBy logic. So I think this way it gives more flexibillity for no extra cost. WDYT?

**Comment by enumag** [comment]
@Majkl578 Yeah, those seem like valid use-cases. 👍

**Pull request merged**
